# Adjusted from the brilliant Ivan Tustanivsky who developed this for Sentry
#
# Credits to https://github.com/outoftheboxplugins/BuildMachines

name: Compile Plugin

on:
  workflow_call:
    inputs:
      # Note: done with matrix config, ideally would be nice if input supports arrays
      # ue_version:
      #   default: "5.3"
      #   type: string

      # if plugin to build lives under a sub-directory in the repo
      plugin_path:
          default: ""
          type: string

# Idea is to run the job in parallel in all three last engine versions, uncomment concurency group to only allow one at a time
# concurrency: 
#   group: linux-compile-${{ github.head_ref }}
#   cancel-in-progress: true 

jobs:
  linux-build-plugin:
    name: Compile (Linux) - ${{ matrix.unreal }}

    if: github.actor == 'mklabs'
    runs-on: [self-hosted, Windows]

    strategy:
      matrix:
        unreal: ['5.1', '5.2', '5.3']

    steps:
      - uses: actions/checkout@v4

      - name: Run Docker container
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          # docker run -td --name unreal-${{ matrix.unreal }} --user root -v ${{ github.workspace }}:/workspace --workdir /workspace/${{ inputs.plugin_path }} ghcr.io/epicgames/unreal-engine:dev-slim-${{ matrix.unreal }}
          docker run -td --name unreal-${{ matrix.unreal }} --user root -v ${{ github.workspace }}:/workspace --workdir /workspace ghcr.io/epicgames/unreal-engine:dev-slim-${{ matrix.unreal }}

      - name: Installing UE CLI
        run: |
          docker exec unreal-${{ matrix.unreal }} pip3 install --upgrade pip
          docker exec unreal-${{ matrix.unreal }} pip3 install ue4cli
          docker exec unreal-${{ matrix.unreal }} ue4 setroot /home/ue4/UnrealEngine

      - name: Package plugin
        id: package-app
        # run: docker exec unreal-${{ matrix.unreal }} ue4 package
        run: docker exec -w /workspace/${{ inputs.plugin_path }} unreal ue4 package

      - name: rm container
        if: always()
        run: |
          docker stop unreal-${{ matrix.unreal }}
          docker rm unreal-${{ matrix.unreal }}