on:
  workflow_call:
    inputs:
      plugin_name:
        default: "${{ github.event.repository.name }}"
        type: string

jobs:
  reusable_workflow_job:
    if: github.actor == 'mklabs'
    runs-on: [self-hosted, Windows]

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Octo Organization

      - name: Check docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

  dump-context:
      runs-on: ubuntu-latest
      steps:
      - name: Dump Inputs context
        env:
          GITHUB_CONTEXT: ${{ toJson(inputs) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  uplugin-json:
      runs-on: ubuntu-latest
      steps:
        - name: get properties
          id: json_properties
          uses: ActionsTools/read-json-action@main
          with:
            file_path: "Path/to/Plugin.uplugin"

        - name: Debug json
          env:
            PLUGIN_CONTEXT: ${{ toJson(steps.json_properties.outputs) }}
          run: echo "$PLUGIN_CONTEXT"